FROM node:12-alpine

RUN apk add git

WORKDIR /app

ARG NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_GOOGLE_API_KEY=$NEXT_PUBLIC_GOOGLE_API_KEY
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_COLLABORATIVE_WSS=$NEXT_PUBLIC_COLLABORATIVE_WSS

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY patches ./patches
RUN yarn install

COPY . .
RUN yarn run build

USER node

EXPOSE 3000

CMD [ "yarn", "run", "start" ]
