FROM node:12-alpine

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY patches ./patches
RUN yarn install

COPY . .
RUN yarn run build:collaborative

USER node

EXPOSE 443

CMD [ "yarn", "run", "start:collaborative" ]
