name: ci

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.node }}-

      - run: yarn install

  lint:
    needs: [install]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}

      - run: yarn run lint:error
      - run: yarn run format:check
      - run: yarn run typecheck

  test:
    needs: [install]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}

      - run: yarn run test:verbose

  build:
    needs: [install]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}

      - run: yarn build
