name: ci

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 15]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Setup cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.node }}-

      - name: Install dependencies
        run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Check code style
        run: yarn run format:check

      - name: Run lint checks
        run: yarn run lint:error

      - name: Check types
        run: yarn run typecheck

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 15]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Setup cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.node }}-

      - name: Install dependencies
        run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run tests
        run: yarn run test:verbose

  build:
    needs: [install]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14, 15]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: Setup cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.node }}-

      - name: Install dependencies
        run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build project
        run: yarn run build
